credentials:
  usernames:
    fljluser:
      email: florencelaryea88@gmail.com
      logged_in: False
      name: Florence Laryea
      password: "$2b$12$z4Y8vLl.q5DSwgejcA6K4eH4LpjD3.Jtw5xkUD9n35.IdKtjO3c7a"
    guestuser:
      email: adubrightkwarrteng11@gmail.com
      logged_in: False
      name: Guest
      password: "$2b$12$1GN64BTXvEzWCRSRzOzoS.Usm0SoikI4lPKmsaBy6yOk3iBs0KNZW" 
    gakuuser:
      email: successkwawu@gmail.com
      logged_in: False
      name: Success Kwawu
      password: "$2b$12$5FkauNTif3Cd7RT9Xmn0u.KAmTJ5MJMo7/7xtRWyuWGGYJg2LkSae" 
cookie:
  expiry_days: 30
  key: random_signature_key # Must be string
  name: random_cookie_name
pre-authorized:
  emails:
  - florence.laryea@azubiafrica.org

