version: '3.7'
services:
  backend:
    build: 
     context: "./backend"
    ports:
     - "8080:8080"
  frontend:
    build:
      context: "./frontend"
    ports:
     - "7000:7000"
    depends_on:
     - backend
    networks:
     - app-network

networks:
  app-network:
    driver: bridge